server:
  port: 8080
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/soc_net}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:pass}
  hikari:
#      register-mbeans: true
    maximumPoolSize: 70
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
logging:
  level:
    ROOT: INFO
    ru.luzhnykh.socialnet.service: INFO
    ru.luzhnykh.socialnet.controller: INFO
