server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soc_net
    username: postgres
    password: pass
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    ru.luzhnykh: DEBUG