spring:
  application:
    name: resources
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hosp}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:pass}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml