server:
  port: 8080
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/soc_net}
    username: ${DB_USER:dbuser}
    password: ${DB_PASS:pass}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    ROOT: INFO