version: '3'

networks:
  net27_2:
    driver: bridge

services:
  db_socnetmaster:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=soc_net
    networks:
      - net27_2
    volumes:
      - F:\OTUS\HighLoad\db\hw27(2)\socnetmaster:/var/lib/postgresql/data
    cpu_count: 1
    mem_limit: 1gb
    restart: unless-stopped
    command:
       -c shared_preload_libraries=pg_stat_statements
       -c pg_stat_statements.track=all
       -c max_connections=200

  db_socnetslave1:
    image: postgres:16
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=soc_net
    networks:
      - net27_2
    volumes:
      - F:\OTUS\HighLoad\db\hw27(2)\socnetslave1:/var/lib/postgresql/data
    cpu_count: 1
    mem_limit: 1gb
    restart: unless-stopped
    command:
       -c shared_preload_libraries=pg_stat_statements 
       -c pg_stat_statements.track=all
       -c max_connections=200
    depends_on:
       - db_socnetmaster

  db_socnetslave2:
    image: postgres:16
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=soc_net
    networks:
      - net27_2
    volumes:
      - F:\OTUS\HighLoad\db\hw27(2)\socnetslave2:/var/lib/postgresql/data
    cpu_count: 1
    mem_limit: 1gb
    restart: unless-stopped
    command:
       -c shared_preload_libraries=pg_stat_statements 
       -c pg_stat_statements.track=all
       -c max_connections=200
    depends_on:
       - db_socnetmaster

  haproxy:
    image: haproxy:2.4
    restart: "no"
    networks:
      - net27_2
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - "4080:80"
    depends_on:
       - db_socnetslave1
       - db_socnetslave2

  app_1:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    networks:
      - net27_2
    environment:
      - DB_URL=jdbc:postgresql://haproxy:80/soc_net
      - DB_USER=postgres
      - DB_PASS=pass
      - LIQUIBASE_ENABLED=true
    depends_on:
      - haproxy